### ISSUE TITLE
include from code.google.com

### ISSUE THREAD

**Issue by caffeineaddiction** [Yelp/dockersh#22]
line 8 of config.go references "code.google.com/p/gcfg" as an include ... however earlier in 2016 code.google.com was shutdown I attempted to switch it for "code.google.com/archive/p/gcfg" however this did not work.

The page references that the project has been migrated to "https://gopkg.in/gcfg.v1"

**Comment by solarkennedy** [comment]
Hmm. Can you make a PR?

**Comment by caffeineaddiction** [comment]
Like I said, my attempt to fix it didnt work, or I would have made a Pull Request.
